version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database_name
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - ./mysql/tmp:/var/lib/mysql
    restart: on-failure
    ports:
      - 3306:3306

  web:
    container_name: web
    image: fabiojanio/php-apache-nodejs:7.2-stretch
    environment:
      # PODE ser prod ou dev, por default assume prod
      - TIPO_AMBIENTE=prod
    volumes:
      - ./projeto:/var/www
      #- ./apache:/etc/apache2/sites-enabled/
    working_dir: /var/www
    depends_on:
      - mysql
    links:
      - mysql
    restart: on-failure
    ports:
      - 80:80